trigger:
  branches:
    include:
      - master

jobs:
  - template: azure/azure-pipelines-npm.yml
    parameters:
      name: Linux_npm
      vmImage: ubuntu-16.04
  - template: azure/azure-pipelines-npm.yml
    parameters:
      name: Windows_npm
      vmImage: vs2017-win2016
  - template: azure/azure-pipelines-npm.yml
    parameters:
      name: macOs_npm
      vmImage: macOS-10.14
  - template: azure/azure-pipelines-yarn.yml
    parameters:
      name: Linux_yarn
      vmImage: ubuntu-16.04
  - template: azure/azure-pipelines-yarn.yml
    parameters:
      name: Windows_yarn
      vmImage: vs2017-win2016
  - template: azure/azure-pipelines-yarn.yml
    parameters:
      name: macOS_yarn
      vmImage: macOS-10.14
