import Ember from "ember";
export default Ember.Mixin.create({
    unitList: [
        'ampoule',
        'bag',
        'bottle',
        'box',
        'bundle',
        'capsule',
        'case',
        'container',
        'cream',
        'each',
        'gel',
        'nebule',
        'ointment',
        'pack',        
        'pair',
        'pallet',
        'patch',
        'pcs',
        'pill',        
        'plastic',
        'polyamp',
        'roll',
        'spray',
        'suppository',
        'suspension',
        'set',
        'syrup',
        'tablet',
        'tray',
        'tube',
        'vial'
    ]
});