#!/bin/sh
# Usage: script/bootstrap
# Ensures all dependencies are installed locally.

set -e

cd "$(dirname "$0")/.."

git pull

if [ -f "package.json" ]; then
  echo "==> Installing packages…"
  npm install
  npm install -g phantomjs-prebuilt


else if [ -f "bower.json" ]; then
  echo "==> Installing bower components…"
  bower install

fi
