#!/bin/sh
# Usage: source ./script/cloud9
# Sets up the development environment on a cloud9 workspace and runs the tests to verify.

npm install -g ember-cli@latest
npm install -g bower

#script/bootstrap
set -e

cd "$(dirname "$0")/.."

git pull

if [ -f "package.json" ]; then
  echo "==> Installing packages…"
  npm install
  npm install -g phantomjs-prebuilt
fi

if [ -f "bower.json" ]; then
  echo "==> Installing bower components…"
  bower install --allow-root
fi

#Set up CouchDB for cloud9 workspace#
sudo su couchdb -c 'touch /var/log/couchdb/couchdb.stdout'
sudo su couchdb -c 'touch /var/log/couchdb/couchdb.stderr'
sudo chown couchdb: /var/log/couchdb
sudo chmod u+w /var/log/couchdb
sudo mkdir -p /var/run/couchdb
sudo chown couchdb:couchdb /var/run/couchdb
sudo sed -i 's_couchdb.stderr_/var/log/couchdb/couchdb.stderr_g' /usr/bin/couchdb
sudo sed -i 's_couchdb.stdout_/var/log/couchdb/couchdb.stdout_g' /usr/bin/couchdb
sudo sed -i 's_BACKGROUND=false_BACKGROUND=true_g' /usr/bin/couchdb
sudo su couchdb -c /usr/bin/couchdb
./script/initcouch.sh

cp ./server/config-example.js ./server/config.js

npm start
