#!/bin/sh
# Usage: source ./script/initcloud9
# Sets up the development environment on a cloud9 workspace

printf "\nInstalling ember-cli...\n"
npm install -g ember-cli@latest

printf "Installing bower...\n"
npm install -g bower

printf "Installing node dependecies...\n"
npm install
npm install -g phantomjs-prebuilt

printf "Installing bower components...\n"
bower install

printf "Setting up CouchDB for cloud9 workspace...\n"
sudo su couchdb -c 'touch /var/log/couchdb/couchdb.stdout'
sudo su couchdb -c 'touch /var/log/couchdb/couchdb.stderr'
sudo chown couchdb: /var/log/couchdb
sudo chmod u+w /var/log/couchdb
sudo mkdir -p /var/run/couchdb
sudo chown couchdb:couchdb /var/run/couchdb
sudo sed -i 's_couchdb.stderr_/var/log/couchdb/couchdb.stderr_g' /usr/bin/couchdb
sudo sed -i 's_couchdb.stdout_/var/log/couchdb/couchdb.stdout_g' /usr/bin/couchdb
sudo sed -i 's_BACKGROUND=false_BACKGROUND=true_g' /usr/bin/couchdb
sudo su couchdb -c /usr/bin/couchdb & sleep 8

printf "Configuring CouchDB for Hospital Run...\n"
./script/initcouch.sh

printf "Create Hospital Run server config file...\n"
cp server/config-example.js server/config.js

printf "Cloud9 initiation completed. You can either start the server or run the tests.\n"
