#!/bin/sh
# Usage: source ./script/setupcloud9
# Sets up the development environment on a cloud9 workspace and runs the tests to verify.


if nvm > /dev/null 2>&1; then
    echo "setting proper node version"
    
else
    echo "Cannot find nvm. This probably means you are running this script in its own shell. Try again with source ./script/setupcloud9"
    return 1
fi


nvm install 6
nvm use 6
nvm alias default 6


sudo mkdir -p /var/run/couchdb
sudo chown couchdb:couchdb /var/run/couchdb


npm install -g npm
npm cache clean -f
npm install -g n
sudo n stable
npm install -g ember-cli@latest
npm install -g bower
npm install
bower install

sudo su couchdb -c /usr/bin/couchdb &
sleep 5

./script/initcouch.sh
cp ./server/config-example.js ./server/config.js

./script/test
